#extensions
dot pie: ".py"
dot talon: ".talon"
dot mark down: ".md"
dot shell: ".sh"
dot them: ".vim"
dot see: ".c"
dot see sharp: ".cs"
dot company: ".com"
dot net: ".net"
dot organize: ".org"
dot ex: ".exe"
dot (bin | bend): ".bin"
dot (jason | jay son): ".json"
dot text: ".txt"
dot MP3: ".mp3"
dot flac: ".flac"
dot wave: ".wav"
