command history: user.history_toggle()
command history clear: user.history_clear()
command history less: user.history_less()
command history more: user.history_more()
history show: user.history_toggle()
history clear: user.history_clear()
history less: user.history_less()
history more: user.history_more()
